name: CI

on:
  # Run on all pull requests that change code.
  pull_request:
    paths-ignore:
      - 'README.md'
      - LICENSE
      - .editorconfig
  # Run every time a code change is pushed.
  push:
    paths-ignore:
      - 'README.md'
      - LICENSE
      - .editorconfig
  # Weekly tests
  schedule:
    # At 5:49am each Thursday
    - cron: '49 5 * * 4'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      pvurl: https://raw.githubusercontent.com/tarleb/perevir/v0.3.0/perevir.lua
    container:
      image: pandoc/minimal:latest-alpine

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: apk add make curl

      - name: Install local perevir
        run: curl --output perevir.lua $pvurl

      - name: Test
        run: make test
